version: "3.8"

services:
  react-app:
    image: node:latest
    command: sh -c "npm i && npm start"
    ports:
      - 9000:9000
    working_dir: /react-app
    volumes:
      - ./:/react-app
    environment:
      - DOCKER_MONGODB_URL=mongodb://mongodb:27017/react-app

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 5040:5040
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/

volumes:
  mongo-config:
  mongo-data: